import uuid from "uuid";
export default [
{
    id: uuid.v4(),
    name: "游走人",
    img: "",
    header_img: "",
    description: "2018，想得到的都需要努力！",
    likes: 25,
},
{
    id: uuid.v4(),
    name: "药家的孩子q祭",
    img: "",
    header_img: "",
    description: "You train to look good,I train to kick your ass",
    likes: 1,
},
{
    id: uuid.v4(),
    name: "pla717",
    img: "",
    header_img: "",
    description: "不忘初心，方得始终",
    likes: 12,
},
{
    id: uuid.v4(),
    name: "老禾在",
    img: "",
    header_img: "",
    description: "忍受的痛苦越多就证明你离自己的梦想越近！",
    likes:7,
},
{
    id: uuid.v4(),
    name: "海环抱着天晨",
    img: "",
    header_img: "",
    description: "锻炼或者死亡。 有一种组数叫极限。",
    likes: 38,
},
{
    id: uuid.v4(),
    name: "海豚公子陶",
    img: "",
    header_img: "",
    description: "Look,if you had one shot,or one opportunity ,To seize everything you ever wanted…In one moment,Would you capture it or just let it slip?",
    likes: 29,
},
{
    id: uuid.v4(),
    name: "脏兵狂魔",
    img: "",
    header_img: "",
    description: "多做一个就有更大可能泡到妞了，加油，在一个",
    likes: 40,
},
{
    id: uuid.v4(),
    name: "我在等风吹",
    img: "",
    header_img: "",
    description: "我要走属于我自己的忍道，一直向前走，不放弃。-——火影",
    likes: 50,
},
{
    id: uuid.v4(),
    name: "kevinmaki",
    img: "",
    header_img: "",
    description: "这句话问的好 我们说每个人都有自己的长处和优点 但我总也看不到自己的优点 那就做点自己能控制的事——坚持",
    likes: 13,
},
{
    id: uuid.v4(),
    name: "dickychen1984",
    img: "",
    header_img: "",
    description: "要么学习、要么健身、灵魂和身体必须有一个在路上！",
    likes: 16,
},
{
    id: uuid.v4(),
    name: "阿泽略略略",
    img: "",
    header_img: "",
    description: "什么也阻止不了我健身、即使是年龄！",
    likes: 42,
},
{
    id: uuid.v4(),
    name: "小麻小瑞子",
    img: "",
    header_img: "",
    description: "现在不玩命，将来命玩你",
    likes: 12,
},
{
    id: uuid.v4(),
    name: "洋葱啊啊哦",
    img: "",
    header_img: "",
    description: "怀着梦想入眠、每天吵醒我的不是闹钟、而是梦想",
    likes: 32,
},
{
    id: uuid.v4(),
    name: "看这里",
    img: "",
    header_img: "",
    description: "即使时光倒流、我也会义不容辞的选择健身这条路、因为这是我唯一能坚持一辈子的事情！",
    likes: 24,
},
{
    id: uuid.v4(),
    name: "思考者猪二",
    img: "",
    header_img: "",
    description: "你不竭斯底里精疲力尽，怎么才能破茧成蝶磐涅重生？",
    likes: 26,
},
{
    id: uuid.v4(),
    name: "回忆_烟草香",
    img: "",
    header_img: "",
    description: "我要走属于我自己的忍道，一直向前走，不放弃。-——火影",
    likes: 21,
},
{
    id: uuid.v4(),
    name: "浩渺无极帝尊",
    img: "",
    header_img: "",
    description: "也许说多了毫无意义、但是只要你敢说出自己的目标、即使有再多的阻拦也没有用、因为你才是你的主角、其他都只能算个配角！",
    likes: 32,
},
{
    id: uuid.v4(),
    name: "乐观的空心301",
    img: "",
    header_img: "",
    description: "时间都去哪了还没好好感受年轻就老了",
    likes: 35,
},
{
    id: uuid.v4(),
    name: "孤单又灿烂的球",
    img: "",
    header_img: "",
    description: "用努力换取成功 然后成功就会像一个巴掌 打在那些曾经看不起你的人的脸上 要多响有多响 要多爽有多爽　！",
    likes: 31,
},
{
    id: uuid.v4(),
    name: "望江门外散人",
    img: "",
    header_img: "",
    description: "当你每天因健身而充实、因没有健身而不自在、相信我、好身材离你不远了！",
    likes: 30,
},
{
    id: uuid.v4(),
    name: "双鱼没有方向感",
    img: "",
    header_img: "",
    description: "要想人前显贵、必须人后受罪 原谅我的复制无罪",
    likes: 31,
},
{
    id: uuid.v4(),
    name: "哭你就输了",
    img: "",
    header_img: "",
    description: "健身完的那种累、是你的进步、是你的突破、是你向着你梦想前进的一个个阶梯！",
    likes: 10,
},
{
    id: uuid.v4(),
    name: "呜呼我次奥",
    img: "",
    header_img: "",
    description: "努力是奇迹的另一个代名词！",
    likes: 12,
},
{
    id: uuid.v4(),
    name: "退场的回忆",
    img: "",
    header_img: "",
    description: "什么是梦想？梦想就是在任何时候你都不会停下对它的追求！如果你放弃了、那只能说明你只是想想而已！",
    likes: 11,
},
{
    id: uuid.v4(),
    name: "圆子妖",
    img: "",
    header_img: "",
    description: "经得住挫折、忍得住寂寞、经的起考验、不被苦难所打倒、不被金钱所左右、不被美色所诱惑、爱健身、爱运动、希望接受挑战、勇敢追求梦想、这才是真正意义上的男人！",
    likes: 16,
},
{
    id: uuid.v4(),
    name: "一个拖延症患者",
    img: "",
    header_img: "",
    description: "在健身的道路上必然会孤单、但这就是你成为少部分成功者的原因！",
    likes: 13,
},
{
    id: uuid.v4(),
    name: "为健身坚持",
    img: "",
    header_img: "",
    description: "在你生命最难的阶段不是没人懂你 而是你自己不懂自己",
    likes: 12,
},
{
    id: uuid.v4(),
    name: "健身的壮壮哥",
    img: "",
    header_img: "",
    description: "成功要想走捷径、那你就得就99%的人没有的毅力、付出99%的人都付出不了的努力！",
    likes: 24,
},
{
    id: uuid.v4(),
    name: "诺德康纳",
    img: "",
    header_img: "",
    description: "有人说年龄是健身的最大门槛、那我就告诉你：你完全可以把“健身、一辈子”定为自己的目标、而这也是楼主的目标！",
    likes: 26,
},
{
    id: uuid.v4(),
    name: "骑士剪刀手",
    img: "",
    header_img: "",
    description: "除非你能在床上挣钱、否则就不要赖在床上！这是我们的苍井老师说的！",
    likes: 8,
},

]