import uuid from "uuid";
export default [
{
    id: uuid.v4(),
    description: "南京也下雪了，好大的雪!",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "骑士剪刀手",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "2018，想得到的都需要努力！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "人生会发光哦",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "为什么吃完饭4个小时了肚子放松状态下还那么大",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "风一样丶男孩子",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "有没有推荐推荐比较准的心率手环的，淘宝上的小米手环之类的怎么样",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "_鹰眼米霍克_",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "太胖了，越来越胖了，所以必须减肥！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "大哥布鲁",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "练成这样得几年",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "爱上学不愛上课",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "你不竭斯底里精疲力尽，怎么才能破茧成蝶磐涅重生？",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "小龙猫hz",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "不努力的女人只有两种结果，穿不完的地摊货和逛不完的菜市场。",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "GusammvpG",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "为了女人！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "长得挺招操儿阿",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "Nothing is impossible",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "天使的爱恋ing",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "身材好了可以买好多好看的衣服~",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "临武老刘",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "世界充满罪恶，只有自己强大，才能生存。",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "黑色的一极",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "我之所以这么坚持做我曾难以坚持的事情，只不过是为了放弃治疗",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "一笑长情",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "不忘初心，方得始终",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "潜力股的胖子",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "You train to look good,I train to kick your ass",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "潜力股的胖子",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "多做一个就有更大可能泡到妞了，加油，在一个",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "哪怕",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "现在不玩命，将来命玩你",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "南哥哦哦哦哦",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "你不竭斯底里精疲力尽，怎么才能破茧成蝶磐涅重生？",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "要想人前显贵、必须人后受罪 原谅我的复制无罪",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "每次当我踏进健身房 我的兽性又回来了",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "一号电池",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "努力是奇迹的另一个代名词！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "最爱Xxb1996",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "在健身的道路上必然会孤单、但这就是你成为少部分成功者的原因！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "引用施瓦辛格的:我热爱痛苦",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "念住1212",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "成功要想走捷径、那你就得就99%的人没有的毅力、付出99%的人都付出不了的努力！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "lucifer_羽_",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "忍受的痛苦越多就证明你离自己的梦想越近！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "AJsRocket",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "当一个人像哮喘时渴望呼吸一样的渴望成功，没有什么可以阻挡他成功。",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "z涛涛的z",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "经历了多少决定了他有多少斤两！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "风光葬礼",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "其实很多时候我都会想些励志的语言激励自己前进！这就是自勉！",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "冉小二1989s",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "胡倩在这里",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "我要走属于我自己的忍道，一直向前走，不放弃。-——火影",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "胡倩在这里",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
]