import uuid from "uuid";
export default [
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "骑士剪刀手",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "人生会发光哦",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "风一样丶男孩子",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "_鹰眼米霍克_",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "大哥布鲁",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "爱上学不愛上课",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "小龙猫hz",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "GusammvpG",
    circle_name: "跑步圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "长得挺招操儿阿",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "天使的爱恋ing",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "临武老刘",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "黑色的一极",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "一笑长情",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "潜力股的胖子",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "潜力股的胖子",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "哪怕",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "南哥哦哦哦哦",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "一号电池",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "最爱Xxb1996",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "恰恰晚风",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "念住1212",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "lucifer_羽_",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "AJsRocket",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "z涛涛的z",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "风光葬礼",
    circle_name: "游泳圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "冉小二1989s",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "胡倩在这里",
    circle_name: "健身圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
{
    id: uuid.v4(),
    description: "",
    img: ["", "", "",],
    address: "上海张江",
    longitude: "",
    latitude: "",
    header_img: "",
    name: "胡倩在这里",
    circle_name: "暴走圈",
    likes: Math.floor(Math.random()*50),
    talk_num: Math.floor(Math.random()*50),
    time: (new Date()).toISOString(),
},
]