import uuid from "uuid";
export default [
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/18-1G221164005396-lp.jpg",
    title: "改善你的硬拉实力：前半程硬拉",
    describe: "之前的我们介绍了架上硬拉，架上硬拉是硬拉向心收缩的后半程，刚来过膝盖然后到最终锁定,架上硬拉可以改善你的伸髋爆发力，发展上背肌群，同时，对于一些髋关节活动度受限的人群是一个不错的变化式",
    subscribe: 450,
    price: 88,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/18-1G221163P15T-lp.jpg",
    title: "卧推技巧：夹紧卧推凳",
    describe: "我们知道要想进行强有力的卧推，让全身充满张力，身体的稳定性十分重要！在之前的课程《卧推时：脚的位置》中我们介绍到卧推中由腿驱动是非常重要的一个技巧，腿部除了负责支撑身体外还有一个作用就是把力量从地面上传导上来！如果你是一个力量举，健力爱好者，或者想让你的卧推举得更重，学习如何利用腿部驱动是非常重要的！",
    subscribe: 420,
    price: 188,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171220001215_1-lp.jpg",
    title: "卧推时起桥技术",
    describe: "常常看到有些人在健身房用了这样的姿势在卧推，也看到世界上很多卧推高手都在用这样的姿势进行卧推，到底是怎么样的呢？这样的卧推意义在哪里？你需要这样做吗？",
    subscribe: 352,
    price: 99,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1FI11PF20-L.jpg",
    title: "探秘练不壮的原因",
    describe: "健身房常常会出现这样的现象：有很大一部分人，明明经常来健身房报道，而且该做的也做了、该流的汗也流了，但为什么几个月下来身体却没什么反应、肌肉丝毫看不出成长的迹象，这到底时为什么？为什么和我同期来的人却好像壮了一圈，我做错什么了吗？",
    subscribe: 200,
    price: 256,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1FH51645170-L.jpg",
    title: "健身知识：核心肌群的解剖",
    describe: "常听到核心肌群训练对于人体很重要，在各种动作甚至运动中，稳定脊椎、骨盆等近端肢体，提供远端的活动度，保证力量传输,但是核心肌群指的是什么？是漂亮的六块腹肌吗？",
    subscribe: 100,
    price: 99,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171115173909_1-lp.jpg",
    title: "改善深蹲核心稳定：3个步骤！",
    describe: "在下蹲的过程中，我们需要所有围绕在脊柱上的肌肉以完美的协调方式协同工作，以防止背部扭曲。如果没有这种持续的合作（核心偷懒），仅仅我们徒手上半身的重量就足以使我们的脊柱崩溃！",
    subscribe: 10,
    price: 199,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G0101G3130-L.jpg",
    title: "硬拉技巧：顶端锁定杠铃！",
    describe: "硬拉可以打造全身的块头和力量，但是前提是标准的动作！人们不喜欢硬拉的原因就是他们不会做硬拉,硬拉是最难学习的训练动作！需要做好很多细节，稍有不慎就会出现各种错误，导致受伤的风险增加！而除了常见的起身阶段之外需要注意很多事情之外，如何完成后半程的锁定也是非常重要的技巧！",
    subscribe: 40,
    price: 185,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171102120116_1-lp.jpg",
    title: "核心力量训练：反向平板支撑",
    describe: "说起核心力量训练，很多人会第一个想到平板支撑，没错平板支撑是一个简单有效的动作，他帮助我们锻炼脊柱的抗伸展核心力量，训练我们前侧核心力量",
    subscribe: 20,
    price: 175,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G20R34P70-L.png",
    title: "提升爆发力：弹震式深蹲！",
    describe: "之前我们给大家介绍了一个非常棒的深蹲训练技巧：停顿式深蹲,在深蹲的最低点停留（hold），保持肌肉张力，消除牵张反射,发展我们向心收缩（底部起身）的力量！今天要给大家介绍另一个不错的深蹲技巧：弹震式深蹲！",
    subscribe: 42,
    price: 259,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G215005I30-L.jpg",
    title: "硬拉新花样：改良版的六角杠硬拉",
    describe: "六角杠铃等同于制造一个空间，方便髋关节主导姿势；双手成自然放松状态，不用刻意改变身体较度去抓握，能够更自在地站起及下蹲。身体倾斜的程度降低，脊椎也能维持中立，召集更多腿部肌群参与。",
    subscribe: 23,
    price: 199,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171106115703_1-lp.jpg",
    title: "挑战你的核心：俯卧靠墙爬行！",
    describe: "在之前的抗伸展核心力量训练中我们介绍了健腹轮推行，杠铃滚轮，药球推行，吊环推行等等一系列的动作！这些都是加强腹肌，强化前侧核心力量非常有效的方法",
    subscribe: 33,
    price: 888,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G0311J6290-L.jpg",
    title: "小动作不简单：4个提示做标准俯卧撑！",
    describe: "俯卧撑是一项广受欢迎的徒手训练动作，其优点但是动作简单，随处可练，而且效果俱佳（能有效的训练我们上肢肌群以及和核心力量）,不过看起来好像是那么回事，事实上很多人在操作俯卧撑时重量而不重质，看似好像能做很多下，其实效果很差！",
    subscribe: 45,
    price: 688,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171103114350_1-lp.jpg",
    title: "减肥心经：不要急着下定决心！",
    describe: "当有一天，你晚上洗澡时看着镜子中的自己，发现出社会后自己的身材开始越来越臃肿，肚子上的肥肉越堆越多。。。突然有一天，你受到了鼓舞，不管是看到朋友瘦了、明星减肥成功、还是因为夏天想要穿上泳装等种种理由都会让你发誓：我要减肥，我一定会瘦下来！！",
    subscribe: 24,
    price: 198,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171023114940_1-lp.jpg",
    title: "硬拉变化式：交叉步硬拉！",
    describe: "硬拉动作除了训练到全身最有爆发力的其中二个肌肉：臀大肌及腿後侧肌群，也激活大腿前侧、核心肌群、背部及肩膀。从头到脚趾的肌肉都帮你照顾到。正确地进行硬拉动作，也有助强化你现实世界的动作模式(举例：提重物)，让你背部受到保护。",
    subscribe: 22,
    price: 188,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171115173909_1-lp.jpg",
    title: "如何提升力量？最大肌力训练的关键",
    describe: "去到健身房训练的人都各有目标，有的人希望自己练的健美一些，肌肉好看块头大，有的人希望改善心肺，肌肉耐力，有的人想要把身上难看的脂肪消减一空，不同的目标都会有不同的训练方式和特点！",
    subscribe: 21,
    price: 198,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G02GR92EI.jpg",
    title: "女性力量训练新手如何入门？",
    describe: "给女性力量训练新手的四个建议！力量训练新手的定义为何呢?力量训练新手是指经常性使用器械式的器材作训练，或是有用自由重量，但是却没学过正确的技巧，及没有经常性做杠铃和徒手训练的人。",
    subscribe: 12,
    price: 175,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1FR51IFK03.jpg",
    title: "高难度双杠臂屈伸：TRX臂屈伸",
    describe: "双杠臂屈伸是上肢训练的黄金动作！不管是各项运动员，健身爱好者或是部队的训练中都必不可少！双杠臂屈伸不仅能够锻炼上肢（胸部，肱三头肌）的力量，还能够帮你建立稳定的肩部核心和核心力量！",
    subscribe: 11,
    price: 153,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4-1G2102324210-L.png",
    title: "trx训练动作图解：8个trx训练动作帮你打造强壮上肢",
    describe: "健身房的器械琳琅满目，杠铃，哑铃，壶玲，各式固定器械都是我们用来作为阻力训练的好工具！这些器械各有各的优点和特色，目的都是帮助我们打造强壮的身躯，除了以上这些常见的训练器械之外，今天要给大家介绍另一个非常棒的训练器械：trx悬挂绳！",
    subscribe: 42,
    price: 88,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171116120600_1.jpg",
    title: "硬拉练哪里？硬拉锻炼哪些肌肉",
    describe: "知道为什么要做一件事情的原因会让你更有动力去执行，所以为什么要做你要搞清楚。很多人认为硬拉是‘背部肌群’的训练又或是认为是‘腿部肌群’的训练，但其实并不算是，Deadlift可以说是全身性的训练，从肩膀到腿的肌群都能够训练到。",
    subscribe: 53,
    price: 89,
},
{
    id: uuid.v4(),
    header_img: "http://p24g9b2pq.bkt.clouddn.com/4_171115173909_1-lp.jpg",
    title: "全面训练你的核心：4分钟平板支撑变化式",
    describe: "平板支撑是风靡全球的运动！也是公认的训练核心力量最简单有效的方式！核心力量：身体中多种肌群协同合作所产生的一种“能力”。",
    subscribe: 42,
    price: 899,
},
]