import uuid from "uuid";
export default [
{
    id: uuid.v4(),
    header_img: "",
    name: "倒下的金针菇",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "尚厉GDthings",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小风Grass",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "lalala1234917",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "想个ID有多难",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "CAs",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "最爱fgh578",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "听风吟酒",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "掠夬",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "世界末丶君子楠",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "SHOW",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "我是个地痞人渣",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "CIRCLE",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "段子加工坊",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "CIRCLE",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "Grouti",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "CIRCLE",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "清纯de小骚年",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "CIRCLE",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},
{
    id: uuid.v4(),
    header_img: "",
    name: "枙子花开",
    host_num: Math.floor(Math.random()*50),
    activity_host: Math.floor(Math.random()*100),
    type: "CIRCLE",
    exercise_time: Math.floor(Math.random()*500),
    fans_num: Math.floor(Math.random()*50),
    choice_num: Math.floor(Math.random()*10),
    img: ["", "", ""],
},

]