import uuid from "uuid";
// 30,name header_img, id和userInfo对应上去。
export default [
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "我没有时间跟你解释 我话不多 没那麽啰嗦 阵地的号角指引我勇往直前 我肩负责任胸挺意志手握使命 我将带头冲锋 我会让你看到我有多了不起 我会让你清楚英雄不是偶像剧 我不需要后人评判我的功过 我会为我自己树碑立传 看我活给你看什麽叫男人",
    likes: 42,
    talk_num: 52,
    share_num: 12,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "人这一辈子，不努力成为别人的楷模，就会成为别人的借鉴！这么长时间，我坚持下来的就只有健身和写字了！我健身并不是为了取悦别人，而是为了取悦自己…我想，大多数人跟我的想法一样！所以，我们有什么理由放弃呢？加油吧…",
    likes: 1,
    talk_num: 24,
    share_num: 152,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "这篇文章是我一直想完善的，第一是为了我自己，因为这个是属于我的故事，方便日后回顾；第二，这次是奔加精来的。",
    likes: 230,
    talk_num: 521,
    share_num: 112,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "为什么会去健身？我以前的身高和体重，数据是178，60，其实正常来说是58.外形自不必说，你可以看下下面这个图片，是我读大学吧，兼职卖联想电脑的时候拍的，高低肩，还有驼背，真的挺严重的，我平时走路就是这个形态，好看不好看，不用我多说吧？驼背经常被家人打，威胁我把背挺直这其实根本不管用。。。",
    likes: 43,
    talk_num: 25,
    share_num: 86,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "起个吸引人的标题真是够困难啊",
    likes: 86,
    talk_num: 786,
    share_num: 45,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "各位，一直心里想结合自己的锻炼见解弄一个系统的锻炼动作库，方便大家选择。之前一直是在准备，最近 第一弹胸动作库已经完成了。其实个人觉得，动作各位在各大网站，贴吧都能看到，我想最关键的是小天根据自己的经验，对这些动作的简析，这些是很重要的，无价之宝。",
    likes: 15,
    talk_num: 453,
    share_num: 78,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "我是学生，平时都是在宿舍，家中训练，主要做俯卧撑，仰卧起坐，还玩玩臂力棒。健身贵在坚持。",
    likes: 45,
    talk_num: 86,
    share_num: 53,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "其实我本身是为了夏天要瘦而走进健身房的，慢慢的，发现越跑越快乐， 现在不去都感觉浑身难受。距离今天，已去健身10天。",
    likes: 45,
    talk_num: 78,
    share_num: 53,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "我在上海天行健任职教练，主要是让大家可以少走弯路，要健康就要控制过之与不及，天天跑步那就叫下肢过劳，但上肢过逸，不能算健身，身是全身，同时饮食，睡眠，心态是一个整体，有的人很瘦怎么练也练不壮，这个人脾胃功能有伤，多是饮食不规律，或睡眠有问题，再练也就那样，我会根据个人情况做解答，有老鸟觉得我的解答有问题我们也能探讨，骂人的无视",
    likes: 45,
    talk_num: 568,
    share_num: 172,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "面对健美明星们的照片，健美爱好者赞叹之余常有一些困惑：这么完美的块形是怎样练出来的？他们的训练计划和练习动作并无特别之处呀，难道有什么诀窍？是的，他们确有诀窍，那就是动作的技术细节。",
    likes: 45,
    talk_num: 78,
    share_num: 534,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "我没有时间跟你解释 我话不多 没那麽啰嗦 阵地的号角指引我勇往直前 我肩负责任胸挺意志手握使命 我将带头冲锋 我会让你看到我有多了不起 我会让你清楚英雄不是偶像剧 我不需要后人评判我的功过 我会为我自己树碑立传 看我活给你看什麽叫男人",
    likes: 45,
    talk_num: 38,
    share_num: 78,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "在胸部训练中，中缝部位可谓“难中之难”。健美明星们胸肌中缝两侧的厚度与整个胸肌相一致，中缝窄而又窄，宛如一线。而练了多年的人整个胸肌往往是越向中间肌肉越薄弱，与两侧的发达程度毫不相符。同样做飞鸟动作，为什么效果相差竟如此之大？原因就在技术细节上,本文就从飞鸟动作的细节谈起。",
    likes: 545,
    talk_num: 35,
    share_num: 45,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "很多人对自己训练细节不屑一顾。不知道那样能给自己带来什么。更多人甚至不知道什么事细节。今天启鑫做这个帖子来分享细节。细节决定成败",
    likes: 45,
    talk_num: 356,
    share_num: 354,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "记录贴，坚持就是胜利。什么都可以丢，就是别丢了自己的身体。小弟懂点搏击，但对健身却完全不懂，所以请吧神开导，高人指点。谢谢啦。今天开始记录，为了在家训练能坚持下去。",
    likes: 453,
    talk_num: 453,
    share_num: 78,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "肌肉是为速度而设计的。你移动重量的速度越快，施加在肌肉上的压力就越大，这与慢速训练的做法恰好相反.",
    likes: 55,
    talk_num: 52,
    share_num: 14,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "在我们日常训练中，不管健身新手和老手总是喜欢优先训练他们的肩部,因为肩部的宽度决定身体横向发展的空间,它对整个身体的V形轮廊，形体的舒展、力度与气势等都有决定性的影响，尤其是对整个背部肌群的发展有举足轻重的作用。但是在实际训练中很多人都会遇到三角肌无论怎么练都没有任何酸痛感觉的经历！",
    likes: 378,
    talk_num: 354,
    share_num: 587,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "我本来想来健身吧2个星期了也没做什么贡献··想自己找些图发上来和吧友分享。然后看到别人博客里有一篇不错但点击率太少了·估计很少吧友看到··我就自己整理下发到吧里由于网速比较慢",
    likes: 785,
    talk_num: 45,
    share_num: 35,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "首先声明，我不是大神，不是老手，只是一个健身一个多月的新手。我的路还远着。只是最近看到一堆高三毕业党大学生党涌进健身吧，纷纷询问无器械怎么进行肌肉练习。今晚心血来潮，与大家分享我的无器械练习方法，物件都是取材于生活。高手无视，老手绕道。当然，此方法只适合健身不到2个月的新手，继续往上，日常生活中的物件已经满足不了需求，还是要跟牙刷买副哑铃，才能继续你的健身之路。",
    likes: 45,
    talk_num: 25,
    share_num: 43,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "很多瘦人都想长胖并有发达的肌肉，但是不知道怎么开始，而作为初学者去健身房又往往心生畏惧",
    likes: 53,
    talk_num: 12,
    share_num: 85,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "生来就大三阳，但是无法限制我对强壮的追求。基本资料：28岁，身高172CM.,体重66KG,",
    likes: 68,
    talk_num: 75,
    share_num: 45,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "潜水1个多月了，今天冒个泡，发个帖子记录下一个月的成果，无图无真相，下面上图，",
    likes: 235,
    talk_num: 45,
    share_num: 12,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "快40岁的我，体重80公斤，身高1.75，腰围2.6，有点胖！我每天下午6点下班后才有时间去健身，健身前要吃点东西45分钟后开始锻炼；",
    likes: 35,
    talk_num: 152,
    share_num: 12,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "首先我们来看看什么是肥胖。大部分人会通过体重来判断自己是否肥胖，实际这并不准确。现实生活中我们可以看到两个体重差不多但是外观肥瘦程度差别很大的人。因此判断是否肥胖，标准应该是体脂肪率，既体脂肪占总体重的百分比。而构成体脂肪的两个部分是皮下脂肪和内脏脂肪。前者影响外观，后者环绕在肝脏等器官周围，是最为危险的脂肪。内脏脂肪如果过多，可以大大提高你患上心血管疾病的几率。",
    likes: 45,
    talk_num: 32,
    share_num: 15,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "本人健身几个月，有时候怕自己坚持不下来，所以在吧里做记录下来，可以每天使得提醒自己健身，也能让吧里的朋友们指教和支持～",
    likes: 88,
    talk_num: 53,
    share_num: 2,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "今天完事后,一个苹果,两个芒果,一袋牛奶",
    likes: 2,
    talk_num: 5,
    share_num: 2,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "从今天开始，以后把自己清晨的锻炼日记写到这里，算是提醒和鼓励自己。也希望更多的朋友在这里建立自己的健身日记，保持每天都锻炼，既健康了自己，也火爆了健身吧。",
    likes: 8,
    talk_num: 4,
    share_num: 6,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "这是一个身材缺乏脂肪富裕的中年男子的健身日记，他不打算成为型男，只想让自己更加健康有形一些，在跑步减脂的同时扩展一下自己的力量能力。这还是一个吝啬的父亲——在健身投资尤其吝啬，总认为可以在自己的身边能够找到商业健身器材的替代品（他的跑鞋也不过19元，你还能要求他什么呢？！）",
    likes: 9,
    talk_num: 4,
    share_num: 2,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "这两年身体越来越弱了,缺乏锻炼的原因,主要因为我太懒了.记得上学时可以在一分钟内完成60个标准俯卧撑,而现在连6个都做不下来.曾经引以为傲的棱角分明的八块腹肌,现在成了一马平川了.为了健康,我要重新开始.",
    likes: 7,
    talk_num: 5,
    share_num: 2,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "各位健身爱好者，大家好！从现在起我将把我的健身经历记录下来，希望各位高手指导一下小弟！",
    likes: 15,
    talk_num: 45,
    share_num: 31,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "每次练完胸 背 只有练的时候酸疼 第二天一点感觉都没有 没有酸疼感 我该如何是好",
    likes: 42,
    talk_num: 12,
    share_num: 11,
},
{
    id: uuid.v4(),
    header_img: "",
    name: "小龙的故事",
    time: (new Date()).toISOString(),
    img: "",
    content: "健身小白，昨天刚报了健身房。经济也请不起私教。我先问问练多久可以变壮。太瘦了。本人身高173cm，才55kg。",
    likes: 42,
    talk_num: 35,
    share_num: 10,
},
]